### PR TITLE
Use consistent plugin class naming, removing 'Bumpybox'

### PR DESCRIPTION
**Pull request by iwootten**
Use consistent naming across all plugin files in preparation for migration to new repo. 

Include the CVEI behaviour DCC and original class name. Remove the studio specific name from classes.

### CODE REVIEW

**Comment by tokejepsen** [comment]
Have you not had any problems with same named plugins? https://github.com/pyblish/pyblish-base/issues/306
If so we should really just replace "bumpybox" with "grill".

**Comment by iwootten** [comment]
Nope, but these classes are all named differently aren't they? 

I think including the project name in their title is overly verbose and only a workaround for the issue you've linked to.

**Comment by tokejepsen** [comment]
> Nope, but these classes are all named differently aren't they?

I initially renamed the plugins to be unique. Having the project name would ensure its unique across other external plugins.

> only a workaround for the issue you've linked to.

Definitely a workaround to an issue I could not solve.

**Comment by iwootten** [comment]
> I initially renamed the plugins to be unique. Having the project name would ensure its unique across other external plugins.

I'm not sure "unique" is the correct term here - anyone is free to create a classname that clashes with a plugin within their own environment. We have no control how a studio names their plugins. Although it's less likely with the project name included.

The class files are unique within this PR aren't they? Seems like a class name clash is really more indicative of a bigger problem. Why for example would someone be using two plugins with the same name? If they represent the same behaviour, then they should work the same, if they're different behaviour, then the plugin is incorrectly named.

We can add the project name in. From my point of view,  I was under the impression naming the classes the same as the filename they're within was a PEP8 convention and including the project name makes them very verbose.

**Comment by tokejepsen** [comment]
Alright, let's go for this :)

**Pull request merged**
