### PR TITLE
Ftrack Review and Thumbnail plugins.

### PR DESCRIPTION
**Pull request by tokejepsen**
**Motivation**

This adds the feature of transcoding and uploading movies for reviews in Ftrack. A thumbnail is also created and set with a separate plugin.

**Testing**

1. Publish an image sequence.

The review movie plugin will work without any changes.

The thumbnail plugin will work, but pyblish-ftrack needs to the updated to https://github.com/pyblish/pyblish-ftrack/pull/61 in order for the thumbnail to get set.

### CODE REVIEW

**Comment by iwootten** [comment]
Doesn't this change negate the need for extract_movie.py?

**Comment by tokejepsen** [comment]
Yeah, kinda of. Although extract_movie.py exclusively transcodes the images, and this does that plus uploading to Ftrack.

We don't use the extract_movie.py, do you?

**Comment by iwootten** [comment]
We do, but I'm going to be changing it soon on our branch so it renders using the farm, same goes for thumbnails - deadline will be generating them.

**Comment by tokejepsen** [comment]
Is this ready for a merge then?

**Comment by iwootten** [comment]
I think that the review plugin should default to being inactive - as it's going to make the contents publicly available on the ftrack subdomain is it not?

**Comment by tokejepsen** [comment]
That is true, the contents will be uploaded to the Ftrack server and available.

Issue is that people are going to forget about it, and assume a previous uploaded version is the current one. You are right that this is probably a per studio preference to have it on by default or not.
Not entirely sure how to deal with a per studio preference of switching a plugin on/off by default.

**Pull request merged**
